spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:postgres}?currentSchema=app
    username: ${POSTGRES_USER:dbuser}
    password: ${POSTGRES_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    out-of-order: true
    schemas: app


mybatis:
  type-handlers-package: com.example.oirs.config.mybatis
  type-aliases-package: com.example.oirs.config.mybatis
  configuration:
    map-underscore-to-camel-case: true